### PR TITLE
fix: mobile responsive of current pages

### PR DESCRIPTION
**Pull request by moonlitgrace**

### CODE REVIEW

**Comment by moonlitgrace** [comment]
@baseplate-admin can you msg me on tg? i've reset everything, can u?

**Comment by baseplate-admin** [comment]
> @baseplate-admin can you msg me on tg? i've reset everything, can u?

Did. found zero response

**Comment by moonlitgrace** [comment]
@baseplate-admin Yea I did, i guess its not working again :(

**Comment by baseplate-admin** [comment]
> @baseplate-admin Yea I did, i guess its not working again :(
but i got your old msgs

What do you suggest in Place?

**Pull request merged**
